Repository The-Robotics-Forum/flutter-ui-templates, pull requests merged in 2022-07, with the labels that each got.

#14 Drawer
  lib/main.dart
  lib/packages/drawer/MyDrawerHeader.dart
  lib/packages/drawer/MyDrawerList.dart
  lib/packages/drawer/drawer.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugins.cmake
Labels: HSOC22-Level-1, HSOC22, Approved

#20 Cart Screen
  lib/dashboard.dart
  lib/packages/cart_screen/cart_screen.dart
Labels: HSOC22, HSOC22-Level-2, Approved

#25 Bottom Navigation Bar
  lib/dashboard.dart
  lib/packages/bottom_navigation_bar/bottom_navigation_bar.dart
  pubspec.lock
  pubspec.yaml
Labels: HSOC22, Approved, HSOC22-Level-3

#31 Settings page
  lib/dashboard.dart
  lib/packages/settings_screen/settings.dart
  pubspec.lock
  pubspec.yaml
Labels: HSOC22, HSOC22-Level-2, Approved

#32 Onboarding Screen
  assets/fonts/Mulish-Light.ttf
  assets/fonts/Mulish-SemiBold.ttf
  assets/images/image1.png
  assets/images/image2.png
  assets/images/image3.png
  lib/packages/onboarding/onboarding_contents.dart
  lib/packages/onboarding/onboarding_screen.dart
  lib/packages/onboarding/size_config.dart
  lib/packages/splash_screen/splash.dart
  pubspec.yaml
Labels: HSOC22, Approved, HSOC22-Level-3

#35 Web View in profile card
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/packages/Profile_Card/profilecard.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: HSOC22, HSOC22-Level-2, Approved

#37 Search bar
  lib/dashboard.dart
Labels: HSOC22-Level-1, HSOC22, Approved

#39 Day/night theme mode
  android/app/build.gradle
  lib/main.dart
  lib/packages/drawer/MyDrawerList.dart
  lib/theme.dart
  pubspec.lock
  pubspec.yaml
Labels: HSOC22, Approved, HSOC22-Level-3

#38 Tab Bar in Dashboard
  lib/dashboard.dart
Labels: HSOC22, HSOC22-Level-2, Approved

#54 Login Screen
  .idea/libraries/Dart_Packages.xml
  .idea/workspace.xml
  projects/ev_stations/lib/main.dart
  projects/ev_stations/lib/screens/login.dart
  projects/ev_stations/pubspec.yaml
  projects/ev_stations/windows/flutter/generated_plugins.cmake
Labels: HSOC22, HSOC22-Level-2, Approved

#55 Dashboard
  projects/ev_stations/assets/car1.jpeg
  projects/ev_stations/assets/car1.png
  projects/ev_stations/assets/car2.jpeg
  projects/ev_stations/lib/main.dart
  projects/ev_stations/lib/screens/users/charging.dart
  projects/ev_stations/lib/screens/users/connection.dart
  projects/ev_stations/lib/screens/users/dashboard.dart
  projects/ev_stations/lib/screens/users/ev_charging_stations.dart
  projects/ev_stations/lib/screens/users/scan_qr_code.dart
  projects/ev_stations/pubspec.lock
  projects/ev_stations/windows/flutter/generated_plugins.cmake
Labels: HSOC22, HSOC22-Level-2, Approved

#56 Connection Screen
  projects/ev_stations/lib/screens/users/connection.dart
  projects/ev_stations/windows/flutter/generated_plugins.cmake
Labels: HSOC22-Level-1, HSOC22, Approved

#69 Navigators and Code Refactor
  projects/ev_stations/lib/screens/users/ChargingProgress.dart
  projects/ev_stations/lib/screens/users/confirming.dart
  projects/ev_stations/lib/screens/users/dashboard.dart
  projects/ev_stations/pubspec.lock
Labels: HSOC22, HSOC22-Level-2, Approved

#72 Predictions
  .idea/libraries/Dart_Packages.xml
  .idea/workspace.xml
  projects/ev_stations/lib/screens/users/predictions.dart
  projects/ev_stations/lib/screens/users/statistics.dart
  projects/ev_stations/pubspec.lock
  projects/ev_stations/pubspec.yaml
Labels: HSOC22, HSOC22-Level-2, Approved

#70 Stations Dashboard
  projects/ev_stations/lib/screens/stations/station_dashboard.dart
  projects/ev_stations/lib/screens/users/drawer.dart
  projects/ev_stations/pubspec.lock
  projects/ev_stations/pubspec.yaml
Labels: HSOC22, Approved, HSOC22-Level-3

#73 Use Media Query Here
  .idea/libraries/Dart_Packages.xml
  .idea/workspace.xml
  projects/ev_stations/lib/screens/login.dart
Labels: HSOC22-Level-1, HSOC22, Approved

#74 Statistics Pie Chart
  projects/ev_stations/lib/screens/stations/statistics.dart
  projects/ev_stations/pubspec.lock
  projects/ev_stations/pubspec.yaml
Labels: HSOC22, Approved, HSOC22-Level-3

#76 #75 resolved
  README.md
Labels: HSOC22, HSOC22-Level-2

#80 Verification Screen
  projects/ev_stations/lib/screens/registration/password.dart
  projects/ev_stations/lib/screens/registration/verification.dart
  projects/ev_stations/lib/screens/splash.dart
  projects/templates/pubspec.lock
  projects/templates/windows/flutter/generated_plugins.cmake
Labels: HSOC22, HSOC22-Level-2, Approved
